export enum ActionTypes {
  SET_INFO = "SET_INFO",
  SET_EDUCATION = "SET_EDUCATION",
  SET_EXPERIENCE = "SET_EXPERIENCE",
  SET_AWARD = "SET_AWARD",
  SET_CERTIFICATION = "SET_CERTIFICATION",
  SET_PROJECT = "SET_PROJECT",
  SET_SKILLS = "SET_SKILLS",
  SET_SUMMARY = "SET_SUMMARY",
  SET_LANGUAGES = "SET_LANGUAGES",
}
